### ISSUE TITLE
BUG - undo/redo disfunctional

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#162]
**Does the issue occur in the electron-app or the web-app?**
- [ ] midi-bricks-electron
- [ ] midi-bricks-web-app
- [x] both

**Can you determine, which version was used?**
Version: 1.2.8-alpha.14

**Expected behavior**
An undo/redo feature should work in all concerns: Layout Mode, Settings Mode, MIDI learn. 

**Additional context**
If the feature is just designed for Layout mode, it should only appear in Layout Mode. 
If it doesn't work properly yet, we shouldn't have it in the App for now.

**Comment by TimSusa** [comment]
Just want to mention, that i know the feature is not perfect. Anyhow, please keep asking yourself the question, if you need any possibility to get any layout-changes undoable or not. If yes, let us create another ticket to improve undo redo behaviour. Otherwise, we could put that into an extra alpha version release and freeze it for now. This is just a MVP!

**Comment by alectroniq** [comment]
It's an important feature, because in Layout mode the Automatic Gravity can completely mess up your entire layout in a second. 
So we should keep it for the future, but exclude it from the releaes, until it works fine.

**Comment by TimSusa** [comment]
at a first shot layout undo is only shown in layout mode, see new page layout release
