### ISSUE TITLE
Build fails on Windows because of environment variable syntax

### ISSUE THREAD

**Issue by emulvihill** [TimSusa/midi-bricks-mono#185]
**Does the issue occur in the electron-app or the web-app?**
- [x] midi-bricks-electron
- [x] midi-bricks-web-app
- [] I do not know nor understand

**Can you determine, which version was used?**
Version: 1.3.28

**Describe the bug**
Build does not work on Windows.  See end of report for fix.

**Steps To Reproduce**
1. 'yarn build'
2. console outputs "REACT_APP_IS_WEB_MODE" is not recognized as an internal or external command..."

**Expected behavior**
build completes

**Screenshots**

**Desktop Version (please complete the following information):**
 - OS: Windows 10

**Additional context**
It's *SO* close to working. All that is needed is to go into the package.json(s) and prepend any ENVVAR=value with 'set ENVVAR=value'.    Because this then breaks Bash shell build, I would suggest instead using 'crossenv' package which should be fairly simple to prepend on affected lines to ensure cross-platform compatibility.   

Or at minimum, just put this workaround prominently in the build instructions, because the research took a lot longer than actually patching the package.json.

I can verify that the build works fine on Windows (even electron app) once this hack is put into the package.json scripts.

**Comment by TimSusa** [comment]
Hey, 

at first thanks for trying to participate. I fixed a lot of stuff and updated it since now almost one year with version 1.3.32.  The thing is, the whole project was never supposed to be built under Windows, only the result should be a windows executable, not more. So there is a lot more stuff to do, to make it run, I think. See there are several "cd" and "cp" instructions going on in the package.json. I mean this is a bad story of a hack, I know for myself. I just wanted to get the shit to run. So my suggestion would be to create a feature issue out of it. Maybe somebody has energy to rip this story off? At the moment, there are issues with higher priority. Sry!

Cheers!
